const course=window.COURSE;const state={chapter:course[0].id,done:new Set(JSON.parse(localStorage.getItem('phys211-done')||'[]'))};
const $=s=>document.querySelector(s);const list=$('#chapterList'),topics=$('#topicList');
function allTopics(){return course.flatMap(c=>c.topics.map((t,i)=>({...t,key:`${c.id}-${i}`,chapter:c.title})))}
function save(){localStorage.setItem('phys211-done',JSON.stringify([...state.done]));renderProgress()}
function renderProgress(){const total=allTopics().length,done=state.done.size,pct=done/total*100;$('#progressText').textContent=`${done} / ${total} 已掌握`;$('#progressBar').style.width=`${pct}%`;const c=course.find(x=>x.id===state.chapter);$('#chapterDone').textContent=`${c.topics.filter((_,i)=>state.done.has(`${c.id}-${i}`)).length}/${c.topics.length}`}
function renderNav(){list.innerHTML=course.map(c=>`<button class="chapter-button ${c.id===state.chapter?'active':''}" data-id="${c.id}"><strong>${c.n}</strong><span>${c.title}</span><small>${c.topics.length}</small></button>`).join('');list.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.chapter=b.dataset.id;render();if(innerWidth<900)document.querySelector('.chapter-view').scrollIntoView({behavior:'smooth'})})}
function renderTopics(c){topics.innerHTML=c.topics.map((t,i)=>{const key=`${c.id}-${i}`,done=state.done.has(key);return `<details class="topic-card"><summary><span class="topic-number">${String(i+1).padStart(2,'0')}</span><span class="topic-title"><strong>${t.t}</strong><span>${t.tag}</span></span><span class="chevron">＋</span></summary><div class="topic-body"><p class="concept">${t.c}</p><div class="formula-card"><p class="formula">${t.f}</p><p>${t.fm}</p></div><div class="example"><h4>典型例题</h4><p>${t.q}</p><ol class="steps">${t.s.map(x=>`<li>${x}</li>`).join('')}</ol></div><div class="mistake"><h4>易错点</h4>${t.m}</div><div class="check"><h4>合上资料自测</h4><p>${t.check}</p><button class="answer-toggle">显示答案</button><p class="answer" hidden>${t.a}</p></div><div class="master-row"><button class="master-button ${done?'done':''}" data-key="${key}">${done?'已掌握 ✓':'标记为已掌握'}</button></div></div></details>`}).join('');topics.querySelectorAll('.answer-toggle').forEach(b=>b.onclick=()=>{const a=b.nextElementSibling;a.hidden=!a.hidden;b.textContent=a.hidden?'显示答案':'隐藏答案'});topics.querySelectorAll('.master-button').forEach(b=>b.onclick=()=>{state.done.has(b.dataset.key)?state.done.delete(b.dataset.key):state.done.add(b.dataset.key);save();renderTopics(c)});topics.querySelectorAll('details').forEach(d=>d.addEventListener('toggle',()=>{d.querySelector('.chevron').textContent=d.open?'−':'＋'}))}
function render(){const c=course.find(x=>x.id===state.chapter);$('#chapterLectures').textContent=c.lectures;$('#chapterTitle').textContent=c.title;$('#chapterSummary').textContent=c.summary;renderNav();renderTopics(c);renderProgress()}
function quiz(){const pool=allTopics(),q=pool[Math.floor(Math.random()*pool.length)];$('#quizTitle').textContent=`${q.chapter} · ${q.t}`;$('#quizQuestion').textContent=q.check;$('#quizAnswer').textContent=q.a;$('#quizAnswer').hidden=true;$('#revealQuiz').hidden=false;$('#quizDialog').showModal()}
$('#randomQuiz').onclick=quiz;$('#revealQuiz').onclick=()=>{$('#quizAnswer').hidden=false;$('#revealQuiz').hidden=true};$('.dialog-close').onclick=()=>$('#quizDialog').close();$('#resetProgress').onclick=()=>{if(confirm('确定清除全部掌握记录吗？')){state.done.clear();save();render()}};
const exam=new Date('2026-08-07T09:00:00+08:00'),now=new Date();$('#daysLeft').textContent=Math.max(0,Math.ceil((exam-now)/86400000));render();
